apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-management-service-config
  namespace: smartedify
  labels:
    app: asset-management-service
    component: config
data:
  NODE_ENV: "production"
  PORT: "3010"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://app.smartedify.com,https://admin.smartedify.com"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  ENABLE_AUDIT_LOG: "true"
  ENABLE_OFFLINE_MODE: "true"
  ENABLE_LLM_CLASSIFICATION: "true"
  ENABLE_PREDICTIVE_MAINTENANCE: "true"
  OTEL_SERVICE_NAME: "asset-management-service"
  OTEL_SERVICE_VERSION: "1.0.0"
  KAFKA_CLIENT_ID: "asset-management-service"
  KAFKA_GROUP_ID: "asset-management-service-group"
  DEFAULT_MAINTENANCE_REMINDER_DAYS: "7"
  MAX_PROVIDERS_PER_SOS: "3"
  SOS_RESPONSE_TIMEOUT_HOURS: "72"
  WORK_ORDER_REMINDER_HOURS: "24"

---
apiVersion: v1
kind: Secret
metadata:
  name: asset-management-service-secrets
  namespace: smartedify
  labels:
    app: asset-management-service
    component: secrets
type: Opaque
stringData:
  DB_HOST: "postgres-primary.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_USERNAME: "asset_management_service"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  DB_NAME: "smartedify_assets"
  REDIS_HOST: "redis-master.cache.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  ENCRYPTION_KEY: "CHANGE_ME_32_CHAR_ENCRYPTION_KEY"
  KAFKA_BROKERS: "kafka-headless.kafka.svc.cluster.local:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.observability.svc.cluster.local:14268"
  IDENTITY_SERVICE_URL: "http://identity-service.smartedify.svc.cluster.local:3001"
  TENANCY_SERVICE_URL: "http://tenancy-service.smartedify.svc.cluster.local:3003"
  FINANCE_SERVICE_URL: "http://finance-service.smartedify.svc.cluster.local:3007"
  HR_SERVICE_URL: "http://hr-compliance-service.smartedify.svc.cluster.local:3009"
  NOTIFICATIONS_SERVICE_URL: "http://notifications-service.smartedify.svc.cluster.local:3005"
  DOCUMENTS_SERVICE_URL: "http://documents-service.smartedify.svc.cluster.local:3006"
  MARKETPLACE_SERVICE_URL: "http://marketplace-service.smartedify.svc.cluster.local:3015"
  ANALYTICS_SERVICE_URL: "http://analytics-service.smartedify.svc.cluster.local:3016"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-management-service
  namespace: smartedify
  labels:
    app: asset-management-service
    component: api
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: asset-management-service
      component: api
  template:
    metadata:
      labels:
        app: asset-management-service
        component: api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3010"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: asset-management-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: asset-management-service
        image: smartedify/asset-management-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3010
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: asset-management-service-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: asset-management-service-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: asset-management-service-config
              key: LOG_LEVEL
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: REDIS_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: JWT_SECRET
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: asset-management-service-secrets
              key: KAFKA_BROKERS
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/assets/health/liveness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/assets/health/readiness
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: uploads
          mountPath: /app/uploads
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: uploads
        emptyDir: {}
      - name: cache
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - asset-management-service
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: asset-management-service
  namespace: smartedify
  labels:
    app: asset-management-service
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 3010
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: asset-management-service
    component: api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asset-management-service
  namespace: smartedify
  labels:
    app: asset-management-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asset-management-service-hpa
  namespace: smartedify
  labels:
    app: asset-management-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asset-management-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: asset-management-service-pdb
  namespace: smartedify
  labels:
    app: asset-management-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: asset-management-service
      component: api

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: asset-management-service-netpol
  namespace: smartedify
  labels:
    app: asset-management-service
spec:
  podSelector:
    matchLabels:
      app: asset-management-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: smartedify
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 3010
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: database
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          name: cache
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - namespaceSelector:
        matchLabels:
          name: kafka
    ports:
    - protocol: TCP
      port: 9092
  - to:
    - namespaceSelector:
        matchLabels:
          name: observability
    ports:
    - protocol: TCP
      port: 14268
  - to:
    - namespaceSelector:
        matchLabels:
          name: smartedify
    ports:
    - protocol: TCP
      port: 3001
    - protocol: TCP
      port: 3003
    - protocol: TCP
      port: 3005
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 3007
    - protocol: TCP
      port: 3009
    - protocol: TCP
      port: 3015
    - protocol: TCP
      port: 3016
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53