version: '3.8'
services:
  test-db:
    image: postgres:15
    container_name: identity-test-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"
    volumes:
      - identity-test-data:/var/lib/postgresql/data

volumes:
  identity-test-data:
