
limits:
  write:
    tenant:
      requests_per_minute: 60
    user:
      requests_per_minute: 30
  read:
    tenant:
      requests_per_minute: 600
    user:
      requests_per_minute: 120
websocket:
  messages_per_second: 1
  burst: 3
