openapi: 3.0.3
info:
  title: SmartEdify Auth API
  version: 1.0.0
  description: API de autenticación de SmartEdify.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://auth.smartedify.global/api
    description: API de producción
  - url: https://staging.auth.smartedify.global/api
    description: API de pruebas
paths:
  /auth/login:
    post:
      summary: Login usuario
      operationId: loginUser
      security:
        - OAuth2AuthorisationCode: [openid, profile]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '200':
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: Petición inválida
        '401':
          description: Credenciales inválidas
components:
  securitySchemes:
    OAuth2AuthorisationCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.smartedify.global/oauth/authorize
          tokenUrl: https://auth.smartedify.global/oauth/token
          scopes:
            openid: Acceso a información básica del usuario
            profile: Acceso a perfil del usuario
